name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/nda-analyzer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Build and push image to Artifact Registry
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd backend
          gcloud builds submit \
          --config cloudbuild.yaml \
          --substitutions=_HF_TOKEN=${HF_TOKEN},_IMAGE=${IMAGE}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nda-analyzer \
            --image ${IMAGE} \
            --region europe-west10 \
            --service-account=${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} \
            --min-instances 1 \
            --memory=2Gi \
            --cpu 2 \
            --execution-environment=gen2 \
            --cpu-throttling off \
            --allow-unauthenticated \
            --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},GCS_BUCKET=${{ secrets.GCS_BUCKET }}